### ISSUE TITLE
cmake ios

### ISSUE THREAD

**Issue by shaojiankui** [forexample/ios-cmake-in-native-xcode#1]
why im use this comand "cmake -B_builds -GXcode .",it will make to a  mac project not a iOS project,how to fix it

**Comment by ruslo** [comment]
Hi,

Just for your information `cmake -B_builds -GXcode .` is not the same as `cmake -H. -B_builds -GXcode`.

What Xcode version are you using?

**Comment by shaojiankui** [comment]
Actually, im building http://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.6-src.tar.gz  for iOS,but try many times didnot ok

**Comment by ruslo** [comment]
If you take a look at [CMakeLists.txt](https://github.com/forexample/ios-cmake-in-native-xcode/blob/master/cmake-ios-project/CMakeLists.txt) of this project you can find this code:

``` cmake
set(CMAKE_OSX_SYSROOT "iphoneos")
set(CMAKE_XCODE_EFFECTIVE_PLATFORMS "-iphoneos;-iphonesimulator")
```

Also take a look at iOS toolchains: https://github.com/ruslo/polly/wiki/Toolchain-list#ios

I'm closing this one since it's not related to the project at all. If you have problems with building `mysql` products you should ask question on the related forums or use another resources like http://stackoverflow.com.
